// <auto-generated />
namespace FilRouge.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _17_04 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_17_04));
        
        string IMigrationMetadata.Id
        {
            get { return "201804171013533_17_04"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
