// <auto-generated />
namespace FilRouge.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class FilRougeV1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FilRougeV1));
        
        string IMigrationMetadata.Id
        {
            get { return "201804101002402_FilRougeV1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
